server:
  port: 8765
  servlet:
    context-path: /user
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8768/eureka/
spring:
  redis:
    host: localhost
    port: 6379
    password: jredis123456
    database: 1
