zk:
  address: localhost:2181
  connect-timeout: 10000
  client:
    registry: true
    root: /im-server
server:
  host: 127.0.0.1
  im-port: 7689
  port: 8900
  heart-beat-time: 18000 # 单位 ms
  servlet:
    context-path: /server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8768/eureka/